language: scala
scala:
- 2.10.4
- 2.11.2
jdk:
- oraclejdk7
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - platform-engineering@digital.cabinet-office.gov.uk
after_success:
- '[[ $TRAVIS_BRANCH == "master" ]] && { sbt publish; };'
env:
  global:
  - secure: jPmA+gF5j3r977AoOndLXHUjzq81J4nlR6zvhkSu6Mwg1QFOPw0oZMAClgm5uTA3gQEdaE7KIG6gy9FCbSHAFW007BMA+2ZWEUrtlQ3cpWjHN53swsJrcYviFw+JpnzEXwkQGZZ8kF12GklEbaO1smCGMBdrg/jKQ1Lu+L6f1Tk=
  - secure: KJUjSRebr1ULzkuYbKW17m1rkKD2IoF5DNRTkeCMKTQwENMvlRTtD3jISyF9YdjHyYx+kKlnc0S7ewOkjc7jLq5tMjqcn0solyHch47JMpu/gY6oUUAMqeC4FPvB2GrYUaovKKWVB1wXJRAhJh5FPbqlrUSwBEyBnmJXwG9mZWw=
