language: scala
scala:
- 2.10.4
- 2.11.2
jdk:
- oraclejdk7
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - platform-engineering@digital.cabinet-office.gov.uk
after_success:
- '[[ $TRAVIS_BRANCH == "master" ]] && { sbt publish; };'
env:
  global:
  - secure: Eg++9ukn+9WQUMo3CeL0eDy7bhJgia/Oh2QOXasvJ8w/00tun8W2qw69lVuxBFUADqXI+O0nfpSmFPpKR3fXLvx9VtpDcs55chR9dtuRZPDYYADDr5GGRZ0JnlF+ad4GlRpVNIOa0S8WVGRp690HI0oKQ7+Aie6IaqNMzvwe8RM=
  - secure: NSVpE3aLsdHJk/+1gX1q3Mvu0VW6XYdJPKbnjx0r8IkQyFhgJDh8BYFIKN7weGg0D/wcuHR//qg8SpOnZJDopDT3LuWP1mSb5oicK6yL+sFDxAKBVtoy9fKqOGgL2BOccYqxP48f3BthBeAMOGaVcip2TxVEtlh04rsh3IQmZvs=
