language: scala
scala:
- 2.10.4
- 2.11.2
jdk:
- oraclejdk7
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - platform-engineering@digital.cabinet-office.gov.uk
after_success:
- '[[ $TRAVIS_BRANCH == "master" ]] && { sbt publish; };'
env:
  global:
  - secure: ILJTu36vjg1/4zUTL9Il4OXbYQemu7rcCLx87kdAB3C+NLk6DrNFTkvV1IQtyjRsH4o0qiLctvyD4hxp0+9eQDQPPeawZl7lzEaLyfBTP7iKsfkHns69k7NcY/L/RBKutRvXwS0kouirJHCSuw8xwZ218t5+PeNlrM6dgcEQ8ZA=
  - secure: bUEpqr2z8+/7mham3YQb423sijdF2JUFQsko47BbRK5eAPNpI2IuvB1PkBCfLX0/oDyRE1zL88Q51simuyCFi3XMOFi2mKEtTJhZbqqzstQXur/z64hBKCZWanrIoLUATR/AV9xeFLDGYOJpJNqPtSj1Q+lMlFVr/fG6LRmTuZE=
